//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFilesEntities1 : DbContext
    {
        public dbFilesEntities1()
            : base("name=dbFilesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StoreImage> StoreImages { get; set; }
        public virtual DbSet<tbl_registration> tbl_registration { get; set; }
        public virtual DbSet<tb_r_travel_request_participant> tb_r_travel_request_participant { get; set; }
    }
}
